In [4]:
import torch
x_data = torch.Tensor([[1.0],[2.0],[3.0]])
y_data = torch.Tensor([[2.0],[4.0],[6.0]])
x_data

tensor([[1.],
        [2.],
        [3.]])

In [19]:
class LinearModel(torch.nn.Module):
    def __init__(self):
        super(LinearModel, self).__init__()#标准写法，super后面的东西是类名
        self.linear = torch.nn.Linear(1,1)
    def forward(self,x):#必须写forward
        y_pred = self.linear(x)
        return y_pred
model = LinearModel()

criterion = torch.nn.MSELoss(size_average = False,reduction = "sum")
optimizer = torch.optim.SGD(model.parameters(),lr = 0.01)#model.parameters 会自动的把所有的参数找出来


In [24]:
for epoch in range(1000):
    y_pred = model(x_data)
    loss = criterion(y_pred, y_data)
    #print(epoch,loss)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    

In [26]:
print("w = ",model.linear.weight.item())
print("b = ",model.linear.bias.item())
x_test = torch.Tensor([[4.0]])
y_test = model(x_test)
print("y_pred = ",y_test.data)

w =  1.9999985694885254
b =  2.97901578960591e-06
y_pred =  tensor([[8.0000]])


In [29]:
import torchvision
train_set = torchvision.datasets.MNIST(root = "/Users/wudamu/Desktop/Pytorch学习",train = True, download = True)
test_set = torchvision.datasets.MNIST(root = "/Users/wudamu/Desktop/Pytorch学习",train = True, download = True)

In [33]:
import torch.nn.functional as F
x_data = torch.Tensor([[1.0],[2.0],[3.0]])
y_data = torch.Tensor([[0.0],[0.0],[1.0]])
class LogisticRegressionModel(torch.nn.Module):
    def __init__(self):
        super(LogisticRegressionModel, self).__init__()
        self.linear = torch.nn.Linear(1, 1)
    def forward(self, x):
        y_pred = F.sigmoid(self.linear(x))
        return y_pred
model = LogisticRegressionModel()
criterion = torch.nn.BCELoss(size_average = False,reduction = "sum")
optimizer = torch.optim.SGD(model.parameters(),lr = 0.01)  
for epoch in range(1000):
    y_pred = model(x_data)
    loss = criterion(y_pred, y_data)
    #print(epoch,loss.item())
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    

In [ ]:
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

class XXX(Dataset)
    def __init__(self，filepath）# 这里面通常是1.读取全部的数据 2.读取数据的地址
        xy = np.loadtxt(filepath,delimititer = ",",dtype = np.float32)
        self.len = xy.shape[0]
        self.x = []
        self.y = []
                 
    def __getitem__(self, index): #取索引的方法 2.取上面的地址之类的
        return x[index] y[index]
                 
    def __len__(self):#取长度的方法
        return self.len

dataset = xxx()
train_loader = DataLoader(dataset=dataset,batch_size=32,shuffle=True,num_workers=2)
                 #shuffle = True 打乱顺序，num_worker 用几个线程
class model()
    pass
for epoch in range(100)
    for i, data in enumerate(train_loader,0) # i 是返回第几次，
        inputs, labey = data    

In [55]:
import torch
from torchvision import transforms #处理图像时候用到的工具
from torchvision import datasets
from torch.utils.data import DataLoader
import torch.nn.functional as F
import torch.optim as optim
transform = transforms.Compose([transforms.ToTensor(),transforms.Normalize((0.1307,),(0.3081,))])# Totensor 变成张量，C*W*H 通道✖️宽*高
train_dataset = torchvision.datasets.MNIST(root = "/Users/wudamu/Desktop/Pytorch学习",train = True, download = False, transform = transform)
train_loader = DataLoader(train_dataset,shuffle = True,batch_size = 32)
test_dataset = torchvision.datasets.MNIST(root = "/Users/wudamu/Desktop/Pytorch学习", train = False, download = False, transform = transform)
test_loader = DataLoader(test_dataset,shuffle   =False, batch_size=32)
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.l1 = torch.nn.Linear(784, 512)
        self.l2 = torch.nn.Linear(512, 256)
        self.l3 = torch.nn.Linear(256, 128)
        self.l4 = torch.nn.Linear(128, 64)
        self.l5 = torch.nn.Linear(64, 10)
        
    def forward(self , x):
        x = x.view(-1,784)
        x = F.relu(self.l1(x))
        x = F.relu(self.l2(x))
        x = F.relu(self.l3(x))
        x = F.relu(self.l4(x))
        return self.l5(x)

model = Net()
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01, momentum=0.05) 

def train(epoch):
    running_loss = 0.0
    for batch_idx, data in enumerate(train_loader, 0):
        inputs, targets = data
        optimizer.zero_grad()
        output = model(inputs)
        loss = criterion(output, targets)
        loss.backward()
        optimizer.step()
        print(batch_idx)
        print(targets)
        running_loss+=loss.item()
        if batch_idx % 300 == 299:
            #print('[%d, %5d loss:%.3f' %(epoch + 1,batch_idx +1 ,running_loss/300))
            running_loss = 0.0

def test():
    correct = 0
    total = 0
    with torch.no_grad():
        for data in test_loader:
            images, labels = data
            outputs = model(images)
            _, predicted = torch.max(outputs.data, dim = 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
            #print("Accuracy on test set:%d %%" % (100*correct/total))
             

    
for epoch in range(1):
    train(epoch)
    test()
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

0
tensor([1, 6, 9, 2, 9, 3, 1, 9, 8, 9, 2, 3, 1, 8, 6, 2, 7, 3, 6, 7, 0, 6, 9, 2,
        2, 0, 3, 4, 6, 4, 1, 0])
1
tensor([9, 8, 9, 8, 4, 2, 7, 4, 4, 6, 1, 1, 1, 6, 1, 9, 1, 6, 1, 7, 8, 0, 9, 8,
        6, 4, 0, 4, 4, 7, 5, 9])
2
tensor([1, 8, 5, 6, 8, 1, 2, 6, 8, 8, 1, 7, 1, 5, 3, 1, 8, 3, 0, 0, 0, 3, 5, 2,
        3, 3, 2, 1, 1, 6, 7, 0])
3
tensor([6, 9, 1, 9, 9, 7, 0, 8, 6, 8, 9, 9, 7, 4, 1, 0, 5, 3, 2, 4, 4, 9, 1, 8,
        0, 0, 6, 2, 1, 2, 7, 9])
4
tensor([1, 2, 5, 5, 4, 7, 2, 6, 4, 1, 0, 8, 8, 6, 2, 9, 4, 5, 0, 4, 1, 8, 6, 1,
        5, 9, 9, 4, 7, 9, 7, 5])
5
tensor([5, 9, 5, 3, 1, 8, 2, 0, 9, 7, 9, 8, 2, 2, 7, 5, 1, 8, 3, 5, 6, 2, 8, 5,
        3, 7, 0, 4, 6, 6, 8, 2])
6
tensor([1, 5, 5, 2, 7, 6, 2, 1, 8, 7, 5, 1, 8, 9, 8, 7, 9, 6, 1, 7, 4, 2, 9, 7,
        4, 1, 5, 9, 9, 5, 2, 2])
7
tensor([2, 6, 8, 1, 9, 5, 5, 4, 4, 8, 3, 3, 2, 4, 1, 3, 4, 7, 1, 3, 0, 4, 7, 1,
        1, 6, 9, 3, 2, 6, 2, 3])
8
tensor([5, 9, 0, 3, 9, 9, 1, 3, 2, 3, 1, 9, 3, 8, 1, 4, 0, 7, 6, 2, 3, 1, 3, 4

79
tensor([7, 5, 4, 3, 8, 6, 4, 8, 7, 9, 5, 8, 9, 9, 4, 8, 6, 0, 2, 1, 8, 2, 3, 9,
        7, 6, 1, 7, 6, 5, 0, 1])
80
tensor([5, 4, 0, 2, 2, 0, 6, 6, 9, 7, 5, 1, 2, 6, 3, 4, 1, 9, 0, 6, 9, 8, 3, 0,
        2, 0, 5, 7, 2, 7, 0, 6])
81
tensor([7, 9, 2, 3, 6, 2, 8, 3, 1, 1, 0, 0, 3, 2, 7, 1, 6, 3, 7, 2, 8, 9, 8, 6,
        9, 4, 5, 8, 4, 7, 6, 4])
82
tensor([0, 7, 6, 0, 4, 2, 5, 0, 7, 9, 6, 3, 3, 6, 8, 2, 9, 1, 7, 1, 0, 2, 6, 4,
        6, 5, 4, 5, 7, 1, 8, 3])
83
tensor([8, 5, 4, 5, 2, 9, 6, 2, 9, 2, 6, 9, 5, 9, 9, 9, 8, 4, 5, 6, 0, 1, 6, 6,
        4, 3, 6, 8, 6, 9, 9, 9])
84
tensor([3, 6, 6, 9, 2, 1, 9, 1, 1, 7, 0, 1, 1, 8, 3, 0, 1, 1, 1, 8, 6, 2, 1, 3,
        2, 5, 7, 4, 7, 5, 7, 0])
85
tensor([0, 7, 1, 1, 0, 8, 9, 9, 5, 7, 6, 3, 8, 1, 3, 0, 7, 1, 6, 9, 5, 2, 3, 8,
        4, 0, 2, 1, 2, 2, 4, 0])
86
tensor([4, 8, 6, 5, 9, 6, 0, 0, 8, 3, 9, 8, 6, 0, 9, 5, 0, 3, 5, 1, 6, 9, 4, 2,
        0, 7, 4, 6, 1, 8, 2, 7])
87
tensor([7, 8, 5, 9, 9, 3, 7, 1, 4, 9, 1, 0, 2, 5, 5, 7, 8, 2, 1, 7, 3

157
tensor([3, 7, 4, 7, 7, 9, 9, 3, 1, 3, 6, 7, 4, 0, 9, 1, 0, 5, 2, 4, 8, 5, 8, 4,
        9, 9, 5, 1, 1, 7, 7, 4])
158
tensor([7, 4, 0, 2, 2, 8, 5, 9, 7, 8, 5, 6, 2, 4, 0, 5, 4, 6, 8, 1, 3, 8, 6, 0,
        2, 1, 5, 7, 2, 3, 3, 4])
159
tensor([7, 1, 5, 1, 6, 1, 8, 4, 9, 7, 8, 7, 1, 2, 8, 0, 8, 7, 8, 6, 6, 2, 0, 4,
        1, 9, 7, 0, 5, 0, 2, 3])
160
tensor([9, 4, 3, 7, 8, 0, 7, 3, 3, 3, 8, 0, 7, 3, 9, 1, 7, 4, 6, 9, 8, 5, 6, 1,
        0, 8, 9, 3, 3, 4, 1, 5])
161
tensor([2, 0, 5, 7, 3, 5, 9, 8, 6, 1, 2, 7, 5, 6, 3, 1, 0, 7, 5, 0, 6, 8, 5, 2,
        0, 7, 9, 7, 5, 8, 4, 1])
162
tensor([7, 9, 3, 1, 8, 8, 2, 2, 8, 9, 2, 5, 0, 5, 4, 8, 0, 0, 6, 4, 2, 1, 5, 1,
        9, 4, 4, 3, 1, 1, 7, 6])
163
tensor([1, 7, 1, 9, 9, 0, 6, 1, 6, 7, 3, 2, 2, 6, 1, 6, 6, 2, 1, 1, 1, 7, 1, 9,
        0, 2, 4, 3, 9, 2, 5, 9])
164
tensor([5, 7, 1, 9, 5, 4, 4, 3, 5, 2, 0, 1, 1, 0, 8, 5, 8, 2, 7, 5, 5, 5, 8, 3,
        2, 3, 5, 0, 2, 2, 2, 1])
165
tensor([6, 7, 8, 3, 0, 6, 3, 5, 3, 5, 9, 4, 7, 4, 4, 3, 5, 9

tensor([9, 4, 9, 5, 9, 8, 4, 1, 3, 7, 6, 5, 3, 5, 7, 6, 0, 2, 8, 3, 5, 7, 9, 0,
        9, 4, 7, 1, 0, 0, 0, 5])
234
tensor([8, 1, 0, 0, 3, 6, 8, 1, 8, 1, 1, 4, 8, 6, 6, 1, 6, 1, 6, 6, 4, 3, 0, 2,
        6, 8, 4, 5, 8, 7, 8, 1])
235
tensor([0, 8, 5, 0, 6, 2, 7, 0, 3, 7, 0, 4, 4, 1, 3, 0, 2, 5, 4, 5, 9, 9, 7, 2,
        7, 8, 4, 8, 7, 3, 3, 0])
236
tensor([0, 6, 2, 2, 4, 7, 7, 6, 7, 3, 3, 6, 8, 1, 7, 5, 8, 3, 1, 4, 3, 9, 3, 8,
        1, 4, 3, 7, 7, 7, 9, 6])
237
tensor([3, 8, 6, 3, 4, 6, 1, 3, 9, 7, 9, 4, 6, 6, 5, 6, 0, 5, 9, 0, 9, 1, 8, 9,
        9, 1, 1, 5, 7, 6, 2, 8])
238
tensor([3, 9, 3, 0, 4, 7, 9, 5, 7, 9, 4, 7, 3, 0, 8, 9, 0, 7, 2, 1, 8, 2, 2, 7,
        4, 1, 4, 0, 3, 2, 4, 7])
239
tensor([8, 6, 6, 1, 1, 1, 4, 8, 9, 8, 7, 6, 7, 2, 6, 8, 1, 0, 7, 1, 5, 0, 2, 4,
        3, 2, 2, 1, 2, 4, 1, 1])
240
tensor([2, 7, 9, 1, 6, 4, 2, 5, 0, 9, 3, 2, 0, 1, 4, 4, 3, 3, 4, 6, 4, 4, 2, 5,
        5, 2, 3, 2, 2, 2, 4, 8])
241
tensor([1, 4, 8, 2, 2, 9, 3, 7, 7, 2, 7, 3, 2, 3, 0, 9, 3, 1, 0,

315
tensor([7, 0, 6, 7, 6, 0, 2, 9, 5, 1, 0, 5, 8, 1, 8, 4, 3, 0, 9, 0, 2, 1, 0, 8,
        8, 5, 3, 5, 7, 8, 6, 3])
316
tensor([4, 8, 7, 7, 8, 7, 3, 0, 1, 7, 3, 2, 9, 8, 4, 9, 8, 5, 9, 9, 1, 1, 7, 5,
        8, 3, 1, 3, 2, 5, 1, 1])
317
tensor([7, 0, 1, 0, 4, 8, 0, 0, 2, 4, 1, 5, 1, 9, 5, 0, 6, 7, 3, 0, 8, 5, 8, 1,
        0, 3, 6, 3, 3, 6, 7, 6])
318
tensor([2, 9, 8, 1, 8, 4, 8, 3, 4, 6, 6, 9, 5, 8, 2, 1, 1, 2, 8, 6, 6, 5, 0, 1,
        3, 5, 3, 3, 7, 8, 6, 8])
319
tensor([8, 9, 3, 4, 5, 2, 2, 1, 2, 3, 2, 6, 4, 3, 0, 9, 3, 9, 5, 3, 8, 3, 6, 7,
        5, 0, 4, 4, 0, 2, 9, 8])
320
tensor([0, 1, 9, 6, 8, 2, 9, 3, 0, 9, 1, 5, 4, 4, 7, 6, 6, 7, 8, 9, 3, 6, 9, 6,
        3, 7, 9, 2, 4, 2, 5, 5])
321
tensor([0, 6, 1, 8, 3, 1, 4, 2, 0, 2, 1, 0, 8, 5, 7, 5, 8, 3, 3, 9, 4, 2, 7, 8,
        2, 6, 9, 7, 5, 2, 4, 2])
322
tensor([5, 1, 8, 8, 7, 0, 2, 2, 3, 9, 2, 6, 7, 7, 4, 4, 2, 3, 2, 6, 4, 3, 5, 2,
        8, 0, 1, 6, 7, 7, 6, 2])
323
tensor([2, 4, 1, 5, 7, 1, 1, 9, 5, 9, 2, 7, 8, 5, 9, 7, 7, 2

397
tensor([0, 6, 4, 5, 1, 8, 0, 8, 8, 7, 8, 0, 1, 9, 6, 6, 5, 6, 2, 9, 2, 4, 2, 9,
        1, 7, 5, 9, 4, 0, 7, 4])
398
tensor([5, 7, 7, 1, 8, 3, 8, 2, 0, 6, 8, 3, 2, 8, 8, 0, 6, 0, 7, 4, 1, 3, 7, 4,
        3, 9, 8, 3, 0, 1, 0, 3])
399
tensor([9, 2, 2, 0, 3, 7, 9, 6, 4, 7, 1, 8, 5, 4, 9, 3, 7, 6, 6, 7, 4, 3, 3, 4,
        1, 2, 1, 1, 1, 6, 9, 3])
400
tensor([6, 4, 6, 6, 9, 6, 7, 1, 7, 9, 2, 3, 8, 0, 3, 4, 4, 4, 7, 0, 7, 8, 2, 6,
        0, 5, 9, 4, 4, 4, 6, 1])
401
tensor([3, 7, 0, 9, 8, 1, 9, 6, 8, 2, 4, 7, 4, 0, 8, 2, 5, 3, 1, 3, 8, 9, 4, 2,
        8, 6, 8, 5, 2, 2, 2, 7])
402
tensor([5, 9, 9, 5, 5, 0, 0, 4, 5, 2, 3, 7, 7, 8, 6, 9, 1, 7, 6, 2, 1, 1, 1, 6,
        8, 7, 5, 5, 8, 2, 4, 9])
403
tensor([3, 0, 1, 1, 8, 3, 3, 3, 5, 6, 6, 1, 1, 1, 0, 6, 2, 7, 5, 2, 3, 2, 7, 4,
        5, 2, 1, 5, 7, 3, 1, 1])
404
tensor([1, 8, 7, 2, 9, 9, 2, 9, 3, 7, 1, 9, 6, 9, 3, 3, 9, 3, 7, 0, 1, 1, 1, 3,
        1, 1, 4, 3, 0, 6, 8, 3])
405
tensor([6, 8, 9, 4, 4, 7, 3, 9, 4, 6, 4, 2, 4, 3, 7, 2, 4, 2

477
tensor([4, 1, 0, 9, 2, 6, 7, 6, 7, 8, 2, 9, 5, 2, 8, 2, 2, 4, 2, 6, 3, 1, 3, 5,
        0, 7, 6, 5, 2, 8, 0, 3])
478
tensor([6, 3, 5, 5, 8, 5, 9, 4, 7, 0, 3, 1, 3, 6, 7, 8, 6, 8, 4, 6, 9, 1, 2, 6,
        6, 9, 4, 5, 6, 9, 4, 7])
479
tensor([0, 5, 7, 0, 5, 3, 0, 8, 6, 4, 7, 3, 0, 8, 2, 6, 6, 6, 4, 1, 7, 6, 2, 1,
        2, 2, 7, 3, 8, 4, 1, 3])
480
tensor([6, 3, 1, 7, 3, 8, 5, 5, 9, 7, 7, 2, 2, 2, 4, 8, 9, 3, 2, 9, 5, 3, 4, 5,
        9, 2, 1, 9, 6, 2, 9, 1])
481
tensor([8, 0, 2, 6, 0, 4, 3, 5, 3, 7, 8, 0, 7, 1, 1, 2, 9, 7, 4, 9, 7, 0, 7, 9,
        9, 8, 7, 8, 1, 9, 2, 8])
482
tensor([3, 7, 3, 9, 5, 2, 1, 2, 6, 9, 4, 3, 5, 1, 5, 1, 6, 1, 9, 2, 5, 5, 2, 0,
        7, 2, 9, 9, 7, 5, 0, 8])
483
tensor([6, 8, 8, 9, 2, 9, 7, 3, 6, 9, 2, 2, 7, 3, 1, 6, 2, 9, 3, 6, 7, 0, 0, 8,
        4, 5, 8, 8, 1, 6, 0, 6])
484
tensor([3, 4, 0, 4, 0, 3, 2, 8, 6, 2, 6, 2, 2, 8, 1, 6, 5, 8, 9, 4, 5, 4, 2, 4,
        0, 5, 3, 8, 7, 9, 0, 8])
485
tensor([7, 9, 4, 7, 2, 8, 5, 8, 7, 9, 4, 8, 3, 5, 8, 1, 0, 9

561
tensor([2, 1, 8, 6, 1, 2, 0, 9, 7, 3, 2, 1, 1, 9, 8, 7, 2, 3, 1, 8, 7, 0, 9, 4,
        7, 4, 0, 4, 9, 6, 8, 8])
562
tensor([3, 6, 8, 1, 2, 4, 9, 7, 3, 8, 2, 0, 4, 3, 7, 7, 1, 6, 8, 0, 3, 8, 2, 2,
        1, 8, 8, 2, 2, 0, 9, 3])
563
tensor([0, 7, 8, 9, 7, 2, 3, 6, 8, 9, 4, 2, 0, 8, 6, 7, 8, 5, 0, 5, 1, 5, 1, 6,
        0, 7, 0, 7, 4, 5, 6, 4])
564
tensor([3, 3, 0, 1, 8, 8, 7, 9, 2, 1, 8, 8, 2, 5, 9, 6, 1, 4, 1, 3, 7, 6, 8, 6,
        3, 5, 3, 8, 5, 6, 5, 7])
565
tensor([3, 4, 1, 9, 8, 8, 0, 6, 8, 6, 0, 1, 6, 6, 4, 7, 1, 2, 6, 4, 8, 6, 4, 0,
        9, 5, 0, 1, 0, 3, 0, 7])
566
tensor([3, 8, 0, 2, 0, 9, 3, 9, 0, 1, 6, 9, 5, 0, 5, 3, 2, 2, 7, 7, 7, 6, 2, 1,
        0, 6, 9, 2, 8, 4, 0, 4])
567
tensor([9, 1, 3, 0, 3, 2, 5, 8, 1, 0, 0, 6, 0, 6, 1, 5, 1, 0, 2, 1, 3, 2, 1, 7,
        0, 2, 0, 3, 6, 6, 7, 4])
568
tensor([3, 0, 6, 8, 4, 2, 7, 8, 6, 7, 5, 9, 6, 0, 5, 2, 3, 7, 5, 8, 7, 0, 7, 6,
        6, 2, 9, 5, 4, 5, 6, 4])
569
tensor([6, 9, 7, 6, 4, 8, 4, 0, 4, 0, 8, 6, 3, 0, 4, 2, 2, 5

640
tensor([2, 3, 2, 3, 4, 6, 2, 1, 9, 4, 2, 0, 8, 1, 7, 2, 2, 4, 1, 2, 1, 0, 3, 1,
        5, 5, 3, 6, 1, 3, 4, 3])
641
tensor([2, 5, 1, 1, 1, 0, 0, 7, 2, 4, 8, 0, 2, 9, 1, 5, 8, 7, 2, 6, 3, 7, 5, 8,
        3, 2, 7, 6, 6, 2, 3, 8])
642
tensor([2, 7, 9, 7, 0, 5, 8, 8, 3, 6, 8, 7, 5, 6, 7, 0, 8, 5, 1, 1, 4, 0, 6, 6,
        2, 2, 8, 4, 6, 2, 6, 1])
643
tensor([9, 1, 5, 5, 4, 0, 8, 1, 9, 9, 3, 1, 8, 6, 7, 3, 9, 0, 3, 5, 1, 3, 2, 0,
        8, 4, 6, 5, 6, 1, 1, 5])
644
tensor([8, 9, 8, 9, 9, 7, 7, 7, 5, 2, 7, 9, 0, 2, 7, 1, 3, 7, 0, 3, 3, 8, 9, 8,
        2, 3, 7, 8, 4, 7, 4, 6])
645
tensor([5, 5, 7, 9, 2, 3, 5, 7, 5, 6, 3, 3, 6, 2, 3, 9, 0, 3, 0, 5, 1, 2, 4, 3,
        7, 2, 6, 5, 7, 2, 7, 6])
646
tensor([0, 1, 7, 9, 6, 4, 2, 2, 4, 9, 3, 5, 8, 3, 2, 7, 9, 2, 4, 0, 5, 1, 3, 1,
        4, 6, 6, 4, 3, 8, 7, 7])
647
tensor([8, 0, 2, 9, 4, 7, 4, 5, 4, 3, 8, 4, 2, 6, 0, 5, 9, 7, 2, 5, 1, 7, 6, 1,
        7, 1, 5, 3, 0, 2, 6, 0])
648
tensor([8, 7, 3, 6, 9, 4, 7, 2, 2, 2, 8, 0, 0, 4, 6, 6, 0, 7

717
tensor([8, 7, 6, 7, 4, 1, 1, 0, 0, 9, 9, 8, 7, 0, 5, 3, 3, 4, 3, 7, 9, 6, 5, 0,
        4, 9, 6, 6, 4, 5, 5, 5])
718
tensor([4, 1, 2, 2, 3, 8, 3, 4, 6, 8, 4, 7, 9, 1, 9, 4, 7, 9, 0, 6, 1, 0, 5, 2,
        5, 8, 0, 6, 2, 4, 7, 8])
719
tensor([1, 4, 9, 9, 1, 7, 5, 0, 0, 6, 4, 2, 7, 0, 7, 4, 8, 4, 3, 4, 8, 5, 4, 7,
        6, 7, 5, 1, 2, 8, 1, 8])
720
tensor([4, 1, 4, 3, 3, 0, 3, 6, 2, 7, 7, 9, 6, 0, 3, 2, 9, 4, 9, 2, 0, 4, 6, 4,
        9, 2, 0, 4, 2, 1, 0, 2])
721
tensor([7, 8, 8, 8, 1, 9, 9, 1, 9, 1, 3, 4, 9, 1, 3, 0, 9, 8, 4, 7, 2, 2, 7, 7,
        1, 6, 9, 4, 8, 0, 0, 9])
722
tensor([7, 9, 6, 1, 7, 7, 3, 8, 1, 9, 1, 4, 5, 9, 9, 1, 5, 7, 3, 5, 7, 9, 1, 2,
        1, 6, 7, 4, 4, 1, 3, 4])
723
tensor([2, 1, 6, 2, 3, 7, 2, 6, 9, 4, 4, 1, 4, 2, 0, 3, 9, 4, 3, 8, 0, 5, 2, 2,
        0, 7, 5, 9, 6, 4, 9, 8])
724
tensor([2, 3, 0, 9, 8, 0, 6, 0, 0, 1, 2, 0, 4, 4, 1, 2, 9, 9, 0, 5, 2, 8, 8, 5,
        3, 8, 9, 6, 5, 5, 8, 8])
725
tensor([0, 2, 3, 7, 7, 4, 1, 7, 2, 0, 2, 9, 0, 7, 1, 3, 9, 7

802
tensor([1, 3, 4, 8, 5, 9, 4, 9, 6, 1, 3, 6, 1, 2, 6, 0, 5, 3, 0, 8, 3, 2, 3, 0,
        6, 5, 4, 8, 2, 4, 8, 9])
803
tensor([9, 4, 4, 5, 8, 8, 6, 8, 4, 1, 2, 9, 6, 6, 3, 1, 5, 6, 5, 1, 4, 7, 8, 3,
        0, 1, 3, 6, 3, 7, 0, 3])
804
tensor([7, 4, 8, 3, 6, 1, 7, 3, 8, 1, 5, 5, 8, 8, 6, 8, 1, 1, 9, 9, 9, 9, 5, 9,
        5, 6, 4, 7, 0, 6, 4, 4])
805
tensor([6, 4, 7, 3, 9, 1, 9, 9, 3, 4, 2, 2, 3, 6, 0, 5, 2, 5, 6, 4, 3, 0, 3, 6,
        4, 4, 4, 7, 4, 8, 8, 2])
806
tensor([2, 4, 8, 3, 4, 5, 9, 8, 5, 1, 5, 0, 0, 3, 7, 1, 7, 5, 9, 8, 6, 8, 2, 4,
        5, 5, 8, 3, 1, 1, 3, 1])
807
tensor([7, 3, 0, 7, 7, 9, 1, 4, 7, 5, 3, 1, 4, 1, 7, 1, 0, 0, 9, 4, 3, 8, 9, 0,
        4, 1, 6, 5, 1, 9, 0, 3])
808
tensor([4, 8, 5, 8, 2, 0, 8, 5, 1, 4, 8, 1, 4, 6, 3, 7, 4, 1, 5, 9, 1, 2, 2, 8,
        8, 1, 7, 7, 0, 7, 1, 0])
809
tensor([7, 2, 3, 4, 5, 2, 5, 4, 2, 5, 5, 9, 9, 2, 5, 5, 9, 5, 1, 4, 4, 0, 0, 6,
        6, 5, 7, 0, 6, 2, 0, 1])
810
tensor([9, 8, 8, 3, 1, 4, 6, 6, 0, 2, 1, 5, 8, 3, 9, 1, 4, 2

884
tensor([0, 8, 9, 7, 9, 6, 4, 6, 6, 7, 2, 1, 7, 9, 0, 5, 9, 0, 1, 8, 5, 7, 8, 4,
        0, 6, 0, 4, 7, 7, 5, 8])
885
tensor([8, 2, 6, 8, 1, 4, 2, 4, 6, 1, 3, 2, 2, 3, 4, 7, 6, 9, 1, 3, 4, 1, 8, 3,
        6, 8, 8, 0, 1, 2, 7, 3])
886
tensor([6, 2, 8, 1, 6, 3, 0, 5, 8, 7, 2, 9, 9, 1, 6, 8, 2, 5, 9, 0, 7, 1, 1, 0,
        6, 2, 1, 7, 5, 2, 6, 9])
887
tensor([9, 7, 4, 1, 7, 1, 7, 7, 2, 3, 4, 1, 9, 5, 1, 1, 4, 1, 5, 4, 4, 5, 2, 5,
        6, 3, 1, 3, 6, 8, 2, 0])
888
tensor([8, 7, 6, 4, 1, 1, 3, 1, 1, 9, 9, 3, 7, 8, 8, 0, 7, 1, 9, 6, 6, 1, 4, 8,
        0, 4, 1, 0, 5, 3, 6, 3])
889
tensor([8, 1, 3, 7, 7, 0, 4, 8, 8, 0, 1, 9, 5, 2, 9, 9, 6, 0, 4, 7, 3, 1, 0, 6,
        4, 7, 6, 3, 7, 0, 0, 5])
890
tensor([3, 8, 0, 6, 8, 1, 2, 2, 9, 1, 8, 9, 5, 5, 1, 0, 9, 7, 4, 5, 5, 1, 0, 1,
        6, 8, 0, 4, 0, 0, 1, 0])
891
tensor([0, 1, 5, 8, 6, 9, 2, 8, 7, 6, 8, 2, 8, 7, 7, 3, 3, 8, 6, 3, 7, 9, 8, 4,
        3, 7, 8, 9, 9, 1, 1, 0])
892
tensor([4, 6, 5, 8, 4, 4, 4, 8, 3, 5, 7, 7, 0, 6, 3, 4, 3, 2

968
tensor([4, 9, 8, 7, 5, 3, 2, 8, 5, 8, 5, 8, 9, 0, 0, 8, 0, 1, 4, 7, 3, 1, 7, 6,
        6, 3, 4, 7, 9, 4, 1, 3])
969
tensor([8, 2, 0, 3, 5, 7, 5, 6, 7, 6, 4, 4, 2, 0, 5, 5, 2, 2, 1, 3, 5, 4, 4, 3,
        6, 7, 9, 4, 7, 9, 1, 9])
970
tensor([6, 5, 5, 0, 4, 8, 4, 0, 8, 7, 5, 7, 6, 6, 0, 5, 6, 5, 4, 0, 5, 5, 9, 9,
        0, 4, 4, 6, 2, 4, 3, 1])
971
tensor([8, 1, 8, 7, 7, 6, 1, 3, 5, 6, 2, 2, 1, 6, 6, 5, 2, 2, 0, 6, 0, 1, 1, 2,
        8, 4, 1, 5, 6, 4, 8, 7])
972
tensor([2, 4, 3, 7, 8, 5, 9, 5, 6, 3, 9, 7, 8, 7, 0, 3, 0, 9, 2, 8, 6, 5, 3, 3,
        5, 5, 4, 1, 5, 0, 2, 5])
973
tensor([3, 2, 0, 4, 5, 1, 1, 6, 7, 1, 0, 3, 3, 0, 6, 9, 8, 9, 2, 8, 1, 1, 9, 4,
        5, 6, 3, 1, 8, 1, 5, 3])
974
tensor([7, 7, 9, 9, 2, 5, 3, 3, 2, 5, 4, 4, 3, 1, 7, 0, 5, 2, 5, 1, 2, 8, 1, 6,
        1, 0, 5, 9, 7, 4, 8, 4])
975
tensor([0, 9, 2, 0, 7, 3, 4, 2, 4, 9, 1, 0, 2, 8, 9, 0, 5, 5, 1, 0, 9, 5, 1, 9,
        1, 2, 6, 1, 8, 6, 5, 9])
976
tensor([2, 6, 9, 1, 6, 5, 3, 7, 7, 9, 4, 1, 9, 2, 6, 7, 4, 9

1049
tensor([8, 6, 4, 8, 0, 2, 5, 1, 8, 9, 0, 3, 6, 8, 6, 3, 5, 0, 5, 0, 7, 4, 9, 5,
        8, 6, 2, 6, 9, 1, 3, 3])
1050
tensor([4, 7, 1, 3, 6, 0, 8, 4, 9, 6, 6, 0, 4, 4, 4, 5, 4, 6, 9, 1, 7, 1, 8, 4,
        2, 3, 8, 7, 1, 9, 1, 9])
1051
tensor([8, 9, 8, 8, 6, 8, 6, 3, 4, 8, 2, 1, 9, 7, 2, 6, 7, 5, 1, 0, 8, 4, 5, 2,
        8, 3, 2, 5, 9, 8, 4, 3])
1052
tensor([0, 0, 5, 2, 1, 3, 9, 7, 7, 0, 0, 2, 9, 1, 5, 0, 7, 6, 8, 3, 5, 0, 3, 5,
        2, 1, 2, 6, 4, 3, 0, 8])
1053
tensor([4, 4, 6, 9, 1, 0, 3, 4, 1, 8, 7, 8, 8, 1, 0, 0, 3, 3, 1, 5, 3, 6, 4, 6,
        0, 2, 9, 1, 6, 1, 2, 2])
1054
tensor([4, 1, 9, 1, 3, 9, 6, 8, 5, 6, 0, 1, 9, 2, 0, 1, 4, 0, 5, 7, 5, 1, 4, 7,
        3, 0, 6, 7, 6, 3, 8, 7])
1055
tensor([1, 5, 7, 1, 5, 4, 5, 4, 1, 0, 4, 3, 3, 0, 1, 7, 2, 0, 6, 4, 4, 0, 9, 8,
        0, 1, 0, 4, 5, 9, 7, 8])
1056
tensor([0, 1, 4, 1, 3, 4, 2, 7, 9, 4, 9, 9, 8, 8, 0, 5, 3, 0, 4, 1, 2, 4, 9, 8,
        0, 8, 8, 9, 3, 9, 3, 8])
1057
tensor([1, 5, 3, 9, 1, 2, 4, 5, 3, 2, 4, 5, 1, 6, 2

tensor([1, 5, 3, 8, 1, 5, 9, 0, 5, 7, 2, 3, 6, 6, 6, 5, 2, 5, 1, 9, 3, 4, 8, 0,
        3, 9, 9, 5, 9, 9, 3, 4])
1123
tensor([8, 8, 2, 7, 0, 3, 0, 3, 0, 2, 2, 4, 9, 1, 3, 8, 4, 2, 8, 8, 9, 9, 1, 4,
        9, 1, 4, 5, 4, 4, 7, 8])
1124
tensor([0, 9, 6, 4, 7, 7, 8, 4, 8, 9, 2, 1, 0, 1, 6, 9, 0, 9, 1, 9, 4, 7, 1, 0,
        7, 7, 7, 7, 7, 0, 7, 7])
1125
tensor([6, 4, 1, 6, 3, 2, 1, 7, 2, 7, 1, 0, 8, 7, 2, 5, 0, 1, 7, 1, 1, 1, 8, 1,
        7, 2, 1, 9, 2, 6, 0, 6])
1126
tensor([5, 5, 6, 6, 2, 2, 9, 2, 2, 9, 9, 5, 5, 0, 4, 1, 3, 4, 8, 4, 6, 5, 3, 4,
        7, 1, 4, 8, 4, 7, 7, 9])
1127
tensor([0, 8, 6, 4, 0, 1, 8, 3, 4, 8, 4, 6, 5, 4, 7, 0, 0, 5, 0, 5, 3, 2, 3, 9,
        4, 2, 9, 0, 2, 9, 2, 0])
1128
tensor([3, 6, 6, 4, 1, 3, 4, 1, 8, 4, 0, 2, 3, 6, 7, 1, 3, 4, 4, 1, 9, 6, 0, 6,
        9, 2, 5, 1, 9, 7, 2, 3])
1129
tensor([3, 7, 1, 3, 9, 9, 5, 5, 9, 8, 5, 3, 0, 6, 7, 2, 3, 2, 3, 6, 1, 5, 3, 7,
        1, 3, 2, 4, 2, 6, 6, 0])
1130
tensor([6, 9, 8, 0, 2, 0, 8, 9, 6, 0, 2, 1, 8, 4, 8, 3, 

1207
tensor([5, 4, 6, 7, 9, 8, 0, 4, 2, 3, 4, 9, 4, 1, 6, 7, 9, 2, 0, 3, 8, 2, 8, 8,
        9, 0, 2, 3, 3, 0, 9, 8])
1208
tensor([2, 9, 1, 4, 5, 2, 1, 8, 5, 7, 2, 1, 1, 5, 4, 9, 7, 8, 3, 5, 2, 1, 1, 1,
        5, 4, 6, 0, 2, 8, 9, 3])
1209
tensor([9, 9, 1, 2, 6, 2, 0, 7, 7, 3, 6, 4, 2, 1, 8, 0, 4, 9, 7, 9, 8, 4, 4, 0,
        7, 2, 0, 1, 8, 0, 7, 9])
1210
tensor([0, 5, 8, 1, 4, 4, 3, 8, 9, 6, 7, 2, 2, 7, 2, 3, 2, 4, 2, 0, 5, 8, 4, 5,
        9, 1, 9, 4, 5, 2, 9, 4])
1211
tensor([9, 4, 3, 1, 4, 9, 4, 2, 4, 2, 5, 6, 3, 8, 0, 0, 6, 8, 8, 2, 3, 6, 6, 2,
        6, 6, 0, 3, 1, 4, 6, 3])
1212
tensor([5, 4, 5, 3, 7, 7, 3, 0, 4, 0, 1, 3, 3, 6, 7, 7, 0, 1, 6, 7, 5, 6, 2, 4,
        6, 7, 0, 9, 6, 7, 0, 8])
1213
tensor([1, 8, 9, 0, 6, 0, 1, 0, 7, 4, 9, 4, 9, 1, 9, 9, 1, 1, 7, 4, 4, 0, 7, 9,
        2, 1, 2, 7, 6, 3, 9, 2])
1214
tensor([8, 5, 4, 9, 4, 2, 2, 6, 1, 1, 9, 0, 6, 6, 5, 1, 2, 3, 4, 8, 0, 4, 0, 6,
        5, 9, 8, 3, 8, 6, 1, 4])
1215
tensor([7, 5, 5, 0, 5, 5, 8, 4, 2, 0, 4, 3, 0, 5, 3

1299
tensor([4, 9, 4, 7, 6, 5, 8, 2, 2, 6, 4, 5, 2, 1, 7, 4, 4, 4, 8, 7, 8, 9, 2, 8,
        9, 8, 5, 4, 1, 5, 1, 2])
1300
tensor([8, 6, 3, 6, 3, 0, 7, 2, 1, 2, 4, 2, 1, 3, 9, 9, 3, 1, 8, 8, 1, 8, 2, 9,
        4, 8, 7, 0, 0, 0, 2, 8])
1301
tensor([6, 3, 3, 4, 8, 4, 6, 0, 1, 2, 5, 1, 2, 7, 7, 9, 8, 8, 1, 1, 1, 5, 0, 3,
        8, 7, 6, 2, 8, 0, 8, 1])
1302
tensor([4, 1, 5, 3, 6, 8, 8, 3, 9, 4, 3, 1, 5, 0, 2, 5, 3, 1, 7, 7, 6, 2, 9, 6,
        2, 9, 4, 5, 4, 1, 4, 3])
1303
tensor([1, 5, 9, 6, 7, 3, 0, 6, 8, 9, 2, 5, 3, 7, 1, 4, 7, 2, 8, 7, 7, 7, 1, 0,
        1, 3, 0, 8, 9, 7, 6, 7])
1304
tensor([6, 0, 9, 7, 2, 0, 8, 9, 1, 0, 0, 3, 4, 9, 7, 3, 2, 2, 3, 7, 6, 4, 9, 5,
        2, 8, 6, 9, 9, 9, 6, 2])
1305
tensor([0, 0, 0, 7, 9, 8, 4, 1, 1, 7, 0, 9, 3, 6, 4, 8, 0, 8, 9, 6, 7, 0, 5, 6,
        8, 5, 8, 0, 5, 0, 0, 4])
1306
tensor([5, 2, 9, 2, 2, 1, 1, 2, 4, 4, 4, 7, 1, 8, 3, 0, 1, 7, 4, 7, 9, 1, 0, 2,
        2, 1, 4, 9, 5, 8, 2, 7])
1307
tensor([5, 3, 1, 5, 8, 1, 9, 1, 6, 1, 0, 2, 6, 9, 9

1369
tensor([3, 1, 3, 7, 3, 3, 4, 7, 5, 4, 6, 2, 2, 8, 3, 3, 7, 4, 2, 2, 7, 4, 3, 6,
        0, 6, 4, 4, 9, 9, 6, 3])
1370
tensor([1, 3, 5, 4, 2, 0, 9, 4, 3, 1, 5, 4, 8, 2, 3, 7, 3, 0, 5, 6, 5, 7, 4, 0,
        5, 4, 0, 8, 0, 8, 1, 9])
1371
tensor([9, 3, 4, 0, 2, 1, 9, 6, 7, 5, 5, 5, 2, 9, 6, 7, 2, 9, 3, 8, 6, 0, 0, 6,
        7, 9, 2, 9, 7, 4, 2, 4])
1372
tensor([1, 8, 0, 1, 4, 4, 5, 4, 4, 1, 1, 8, 8, 4, 5, 9, 8, 6, 5, 9, 4, 5, 9, 9,
        7, 0, 4, 0, 5, 2, 6, 5])
1373
tensor([3, 7, 2, 9, 6, 2, 0, 3, 6, 3, 8, 2, 0, 0, 2, 0, 5, 9, 9, 8, 3, 5, 5, 4,
        9, 8, 8, 7, 2, 1, 1, 7])
1374
tensor([6, 6, 0, 4, 3, 5, 6, 8, 0, 7, 4, 2, 3, 9, 5, 6, 6, 9, 1, 6, 2, 2, 7, 4,
        1, 6, 0, 7, 0, 0, 1, 6])
1375
tensor([8, 3, 8, 5, 6, 0, 8, 8, 1, 2, 6, 5, 8, 1, 2, 0, 5, 7, 1, 6, 8, 3, 1, 2,
        7, 6, 6, 6, 8, 6, 8, 2])
1376
tensor([3, 9, 0, 5, 2, 8, 6, 5, 4, 1, 4, 6, 3, 8, 6, 6, 0, 9, 7, 1, 8, 7, 8, 6,
        3, 7, 7, 7, 1, 0, 0, 0])
1377
tensor([7, 6, 0, 6, 4, 9, 2, 9, 4, 8, 2, 4, 1, 1, 4

1443
tensor([9, 3, 4, 9, 9, 5, 1, 3, 7, 2, 3, 3, 8, 5, 9, 2, 1, 0, 6, 8, 3, 2, 7, 9,
        7, 9, 0, 3, 7, 0, 9, 1])
1444
tensor([7, 9, 3, 5, 0, 3, 8, 4, 0, 8, 8, 1, 2, 9, 4, 3, 4, 9, 6, 3, 7, 4, 6, 8,
        9, 4, 3, 2, 4, 0, 3, 0])
1445
tensor([8, 8, 8, 2, 8, 8, 4, 3, 8, 3, 0, 7, 4, 9, 1, 2, 1, 2, 6, 1, 5, 0, 7, 9,
        4, 0, 0, 0, 7, 1, 0, 8])
1446
tensor([8, 9, 6, 3, 1, 9, 4, 6, 5, 3, 1, 8, 9, 2, 8, 2, 7, 0, 9, 9, 8, 0, 7, 8,
        7, 4, 4, 9, 3, 0, 6, 8])
1447
tensor([6, 2, 2, 4, 2, 3, 6, 2, 9, 8, 4, 9, 5, 0, 0, 4, 0, 1, 2, 3, 0, 4, 0, 2,
        2, 7, 3, 4, 0, 3, 3, 2])
1448
tensor([3, 3, 8, 4, 9, 2, 7, 6, 1, 5, 4, 1, 7, 7, 4, 4, 3, 3, 6, 3, 4, 3, 9, 9,
        1, 4, 7, 5, 1, 4, 7, 9])
1449
tensor([8, 3, 3, 0, 9, 3, 4, 0, 4, 3, 8, 9, 0, 6, 2, 0, 8, 1, 2, 0, 3, 3, 9, 9,
        8, 8, 8, 5, 9, 9, 1, 0])
1450
tensor([3, 1, 1, 6, 9, 2, 7, 4, 3, 6, 7, 5, 9, 8, 2, 4, 0, 9, 8, 6, 4, 2, 5, 3,
        4, 3, 0, 3, 2, 4, 0, 6])
1451
tensor([9, 5, 5, 0, 6, 8, 2, 6, 8, 9, 6, 8, 4, 6, 9

1519
tensor([6, 8, 8, 1, 5, 1, 1, 2, 4, 3, 4, 0, 3, 7, 8, 7, 3, 3, 2, 4, 7, 9, 3, 6,
        4, 9, 3, 8, 7, 3, 5, 6])
1520
tensor([9, 2, 2, 3, 3, 9, 6, 6, 0, 4, 0, 1, 8, 2, 9, 9, 0, 9, 1, 8, 9, 9, 6, 1,
        4, 6, 2, 9, 0, 1, 2, 8])
1521
tensor([3, 1, 2, 3, 4, 6, 5, 1, 4, 8, 7, 4, 4, 5, 0, 3, 3, 7, 8, 7, 3, 7, 5, 5,
        3, 5, 5, 8, 3, 4, 8, 2])
1522
tensor([3, 7, 9, 8, 3, 3, 3, 6, 8, 9, 8, 4, 3, 3, 1, 1, 3, 1, 6, 9, 7, 2, 6, 7,
        1, 7, 9, 7, 5, 6, 8, 1])
1523
tensor([3, 3, 8, 8, 6, 2, 3, 9, 7, 8, 6, 3, 3, 1, 8, 8, 8, 7, 4, 5, 1, 7, 9, 0,
        7, 1, 8, 5, 3, 3, 6, 8])
1524
tensor([0, 0, 6, 6, 2, 6, 0, 5, 6, 4, 4, 0, 7, 4, 3, 1, 4, 1, 5, 8, 0, 2, 7, 0,
        6, 6, 8, 8, 0, 8, 2, 7])
1525
tensor([0, 1, 2, 6, 8, 4, 4, 5, 5, 3, 1, 1, 7, 6, 9, 8, 8, 1, 2, 2, 0, 1, 6, 4,
        6, 1, 1, 8, 1, 9, 0, 2])
1526
tensor([3, 5, 7, 6, 1, 8, 6, 9, 4, 6, 3, 7, 0, 3, 3, 1, 5, 7, 9, 4, 1, 9, 5, 6,
        2, 1, 7, 6, 6, 6, 7, 0])
1527
tensor([1, 4, 4, 6, 3, 8, 5, 6, 1, 9, 1, 6, 3, 2, 2

tensor([0, 1, 5, 7, 5, 6, 1, 5, 9, 6, 8, 6, 8, 0, 8, 7, 5, 9, 2, 9, 4, 4, 8, 9,
        1, 4, 1, 6, 6, 1, 0, 3])
1600
tensor([1, 3, 1, 4, 7, 5, 0, 1, 1, 9, 6, 9, 1, 5, 1, 9, 0, 4, 8, 7, 3, 2, 1, 1,
        3, 2, 0, 4, 0, 2, 3, 3])
1601
tensor([2, 6, 3, 3, 7, 7, 4, 5, 9, 6, 0, 2, 8, 4, 9, 4, 0, 9, 1, 1, 7, 5, 7, 8,
        9, 9, 5, 5, 5, 7, 4, 5])
1602
tensor([0, 7, 1, 8, 8, 1, 2, 8, 2, 2, 9, 7, 5, 1, 0, 4, 4, 2, 1, 6, 3, 7, 8, 9,
        8, 4, 2, 9, 4, 1, 5, 4])
1603
tensor([5, 4, 4, 3, 1, 2, 7, 1, 9, 4, 6, 1, 9, 2, 9, 3, 2, 2, 8, 3, 3, 8, 7, 5,
        6, 7, 6, 3, 4, 2, 2, 7])
1604
tensor([7, 4, 4, 4, 1, 0, 0, 5, 5, 2, 3, 5, 8, 3, 1, 9, 7, 7, 5, 1, 5, 6, 0, 7,
        4, 9, 6, 9, 4, 7, 9, 2])
1605
tensor([5, 3, 4, 4, 0, 3, 2, 1, 3, 2, 1, 2, 3, 6, 3, 0, 3, 2, 3, 2, 6, 0, 5, 1,
        2, 2, 0, 6, 7, 1, 7, 8])
1606
tensor([6, 0, 3, 7, 3, 5, 0, 6, 8, 1, 1, 1, 8, 3, 5, 8, 2, 0, 6, 5, 9, 4, 5, 3,
        4, 2, 6, 6, 7, 1, 1, 6])
1607
tensor([2, 1, 3, 1, 6, 7, 2, 9, 6, 6, 4, 4, 9, 8, 9, 1, 

1677
tensor([3, 9, 5, 9, 7, 8, 2, 6, 7, 1, 9, 7, 6, 4, 7, 4, 4, 9, 8, 2, 1, 6, 9, 2,
        8, 3, 7, 3, 7, 5, 4, 8])
1678
tensor([9, 7, 9, 9, 2, 2, 5, 4, 2, 2, 2, 1, 9, 3, 3, 4, 9, 7, 3, 0, 6, 0, 3, 7,
        0, 3, 9, 3, 1, 6, 5, 8])
1679
tensor([3, 7, 0, 7, 4, 7, 8, 0, 1, 5, 9, 8, 2, 0, 7, 8, 4, 7, 7, 9, 8, 2, 7, 8,
        6, 8, 8, 4, 9, 6, 8, 8])
1680
tensor([0, 6, 5, 2, 4, 3, 4, 1, 3, 0, 0, 0, 3, 6, 7, 6, 7, 0, 3, 8, 3, 9, 2, 2,
        6, 8, 7, 0, 7, 3, 1, 5])
1681
tensor([8, 1, 5, 8, 1, 7, 4, 4, 8, 1, 1, 2, 6, 3, 3, 1, 4, 4, 3, 8, 1, 7, 3, 0,
        5, 8, 2, 4, 6, 3, 1, 7])
1682
tensor([9, 0, 6, 5, 6, 4, 4, 8, 2, 1, 2, 4, 1, 0, 1, 3, 7, 4, 0, 6, 9, 0, 4, 8,
        5, 0, 6, 2, 8, 8, 9, 7])
1683
tensor([6, 5, 8, 7, 0, 6, 7, 3, 8, 3, 2, 2, 5, 1, 4, 5, 3, 1, 5, 1, 8, 6, 1, 2,
        6, 8, 4, 6, 1, 4, 5, 2])
1684
tensor([9, 0, 6, 8, 9, 4, 9, 1, 5, 1, 6, 7, 0, 5, 4, 5, 7, 0, 4, 4, 7, 4, 5, 2,
        3, 4, 9, 0, 3, 0, 2, 1])
1685
tensor([8, 4, 8, 9, 2, 2, 4, 4, 4, 6, 1, 8, 6, 7, 1

1753
tensor([5, 1, 7, 0, 3, 9, 5, 4, 6, 2, 1, 1, 2, 7, 4, 8, 3, 5, 1, 0, 4, 1, 6, 8,
        7, 4, 6, 2, 6, 0, 9, 1])
1754
tensor([4, 1, 9, 1, 6, 3, 4, 6, 6, 6, 0, 9, 7, 9, 0, 5, 3, 7, 2, 6, 5, 7, 5, 9,
        7, 9, 7, 1, 2, 5, 9, 7])
1755
tensor([0, 7, 0, 1, 4, 5, 6, 7, 6, 5, 4, 9, 9, 6, 1, 7, 9, 9, 6, 6, 6, 3, 9, 7,
        1, 0, 5, 7, 3, 6, 5, 4])
1756
tensor([6, 2, 7, 8, 1, 0, 5, 1, 2, 2, 7, 2, 6, 1, 4, 4, 7, 9, 1, 8, 7, 0, 0, 8,
        0, 0, 6, 1, 2, 3, 9, 1])
1757
tensor([1, 4, 1, 6, 9, 1, 3, 2, 0, 4, 0, 3, 2, 7, 0, 7, 2, 4, 4, 4, 9, 8, 3, 6,
        8, 1, 4, 6, 1, 5, 0, 3])
1758
tensor([5, 4, 4, 8, 7, 2, 9, 2, 4, 9, 4, 6, 8, 1, 8, 9, 8, 2, 6, 9, 7, 7, 7, 1,
        7, 2, 7, 3, 6, 8, 2, 5])
1759
tensor([6, 4, 6, 0, 4, 4, 4, 1, 5, 1, 5, 9, 0, 9, 9, 7, 5, 6, 9, 6, 3, 9, 4, 5,
        0, 4, 3, 5, 7, 3, 7, 7])
1760
tensor([9, 2, 4, 3, 3, 8, 3, 7, 8, 9, 8, 9, 7, 4, 7, 9, 5, 4, 4, 6, 7, 8, 7, 8,
        4, 4, 8, 7, 7, 7, 9, 0])
1761
tensor([5, 9, 9, 9, 2, 5, 9, 1, 3, 9, 9, 2, 5, 7, 9

1823
tensor([9, 3, 6, 4, 7, 1, 1, 7, 8, 3, 1, 5, 1, 8, 5, 3, 8, 7, 4, 4, 7, 7, 1, 6,
        3, 7, 0, 9, 6, 6, 2, 2])
1824
tensor([7, 4, 9, 8, 4, 9, 5, 5, 3, 0, 2, 8, 6, 7, 8, 6, 2, 3, 3, 9, 0, 6, 8, 7,
        0, 4, 4, 8, 3, 7, 5, 5])
1825
tensor([5, 8, 8, 2, 3, 8, 2, 5, 7, 8, 6, 8, 6, 0, 8, 6, 3, 8, 2, 1, 8, 2, 8, 6,
        9, 1, 4, 6, 5, 3, 9, 1])
1826
tensor([8, 8, 1, 3, 2, 0, 1, 7, 0, 2, 1, 1, 9, 2, 0, 1, 0, 8, 9, 8, 4, 9, 1, 0,
        5, 3, 0, 8, 6, 6, 5, 8])
1827
tensor([1, 1, 3, 1, 7, 7, 4, 3, 0, 0, 9, 1, 8, 3, 8, 7, 0, 6, 9, 1, 9, 7, 4, 2,
        1, 0, 2, 9, 4, 2, 2, 9])
1828
tensor([1, 4, 0, 6, 1, 9, 6, 6, 9, 0, 9, 3, 3, 6, 6, 9, 1, 5, 2, 7, 9, 6, 6, 7,
        7, 9, 1, 3, 4, 0, 1, 1])
1829
tensor([6, 3, 0, 8, 5, 5, 9, 5, 6, 5, 6, 2, 1, 5, 5, 0, 4, 4, 0, 9, 8, 1, 7, 2,
        0, 8, 2, 2, 2, 3, 4, 7])
1830
tensor([8, 1, 7, 8, 7, 3, 4, 7, 8, 3, 9, 1, 9, 4, 5, 4, 8, 9, 1, 5, 0, 1, 7, 1,
        7, 0, 3, 1, 9, 2, 5, 0])
1831
tensor([9, 8, 3, 5, 1, 8, 5, 8, 2, 6, 1, 3, 5, 2, 0

In [48]:
print(train_loader)

In [111]:
from torch.utils.data import DataLoader
from torch.utils.data import Dataset
import torch

train_x = [torch.tensor([1, 2, 3, 4, 5, 6, 7]),
           torch.tensor([2, 3, 4, 5, 6, 7]),
           torch.tensor([3, 4, 5, 6, 7]),
           torch.tensor([4, 5, 6, 7]),
           torch.tensor([5, 6, 7]),
           torch.tensor([6, 7]),
           torch.tensor([7])]
def collate_fn(train_data):
    train_data.sort(key=lambda data: len(data), reverse=True)
    data_length = [len(data) for data in train_data]
    train_data =  torch.nn.utils.rnn.pad_sequence(train_data, batch_first=True, padding_value=0)
    print(train_data, data_length)
    return train_data, data_length
class MyData(Dataset):
    def __init__(self, train_x):
        self.train_x = train_x

    def __len__(self):
        return len(self.train_x)

    def __getitem__(self, item):
        return self.train_x[item]
        
train_data = MyData(train_x)
train_dataloader = DataLoader(train_data, batch_size=2, collate_fn=collate_fn)
for data, length in train_dataloader:
    print(data)
    print(length)
    
    





tensor([[1, 2, 3, 4, 5, 6, 7],
        [2, 3, 4, 5, 6, 7, 0]]) [7, 6]
tensor([[1, 2, 3, 4, 5, 6, 7],
        [2, 3, 4, 5, 6, 7, 0]])
[7, 6]
tensor([[3, 4, 5, 6, 7],
        [4, 5, 6, 7, 0]]) [5, 4]
tensor([[3, 4, 5, 6, 7],
        [4, 5, 6, 7, 0]])
[5, 4]
tensor([[5, 6, 7],
        [6, 7, 0]]) [3, 2]
tensor([[5, 6, 7],
        [6, 7, 0]])
[3, 2]
tensor([[7]]) [1]
tensor([[7]])
[1]


In [112]:
import torch
import torch.nn as nn

batch_size = 2 # 批量长度
max_length = 3 # 序列最大长度
hidden_size = 4 # 隐藏层大小
n_layers = 1 # 层数
input_test = torch.tensor([[1., 2., 3.], [1., 0., 0.]])
input_in = torch.tensor([[1., 2., 3.], [1., 0., 0.]]).unsqueeze(-1)
print(input_in.shape)
print(input_in)
seq_length = [3, 1]
input_pack = nn.utils.rnn.pack_padded_sequence(input_in, seq_length, batch_first=True)
print("input_pack",input_pack)
"""
rnn = nn.RNN(1, hidden_size, n_layers, batch_first = True)
h0 = torch.randn(n_layers, batch_size, hidden_size)
print("h0", h0)
# forward
out, hn = rnn(input_pack, h0)
print("out", out)
print("hn", hn)
# unpack
out_unpack = nn.utils.rnn.pad_packed_sequence(out, batch_first=True)
print(out_unpack)

# 结果
torch.Size([2, 3, 1])"""

torch.Size([2, 3, 1])
tensor([[[1.],
         [2.],
         [3.]],

        [[1.],
         [0.],
         [0.]]])
input_pack PackedSequence(data=tensor([[1.],
        [1.],
        [2.],
        [3.]]), batch_sizes=tensor([2, 1, 1]), sorted_indices=None, unsorted_indices=None)


'\nrnn = nn.RNN(1, hidden_size, n_layers, batch_first = True)\nh0 = torch.randn(n_layers, batch_size, hidden_size)\nprint("h0", h0)\n# forward\nout, hn = rnn(input_pack, h0)\nprint("out", out)\nprint("hn", hn)\n# unpack\nout_unpack = nn.utils.rnn.pad_packed_sequence(out, batch_first=True)\nprint(out_unpack)\n\n# 结果\ntorch.Size([2, 3, 1])'

In [93]:
a=torch.tensor([[1,2,3],[3,4,5]])
a




tensor([[1, 2, 3],
        [3, 4, 5]])

In [ ]:

for data, length in train_dataloader:
    data = torch.nn.utils.rnn.pack_padded_sequence(data, length, batch_first=True)
    print(data)
    


In [117]:
mask = torch.ByteTensor(7).fill_(0)
mask[1].size(0)

tensor(0, dtype=torch.uint8)